language: rust
sudo: false
matrix:
  include:
    - rust: 1.2.0
    - rust: 1.4.0
    - rust: stable
      env:
       - FEATURES='quickcheck'
    - rust: beta
    - rust: nightly
      env:
       - FEATURES='unstable quickcheck'
       - BENCH=1
branches:
  only:
    - master
script:
  - |
      cargo build --verbose &&
      cargo test --verbose &&
      ([ -z "$FEATURES" ] || cargo build --verbose --features "$FEATURES") &&
      ([ -z "$FEATURES" ] || cargo test --verbose --features "$FEATURES") &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES")
