tab_spaces = 2
max_width = 120
fn_call_width = 60
newline_style = "Unix"
take_source_hints = false
write_mode = "Overwrite"
fn_brace_style = "SameLineWhere"
fn_args_density = "Compressed"
fn_args_layout = "Visual"
fn_single_line = true
single_line_if_else = true
where_layout = "HorizontalVertical"
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
enum_trailing_comma = false
match_block_trailing_comma = false
match_wildcard_trailing_comma = false
