language: rust
sudo: false
matrix:
  include:
    - rust: 1.26.0
    - rust: stable
    - rust: nightly
branches:
  only:
    - master
script:
  - |
      cargo build -v --features "$FEATURES" &&
      cargo test -v --features "$FEATURES" &&
      cargo test -v --release --features "$FEATURES"
