name: Rust

on:
  push:
    branches: [main]
    paths: ["**.rs", "Cargo.toml", ".github/workflows/rust.yml"]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt-get install coinor-cbc coinor-libcbc-dev
          rustup component add rustfmt
      - name: Build
        run: cargo build --all-features --tests
      - name: Run tests # test on a single thread. See: https://github.com/KardinalAI/coin_cbc/issues/9
        run: cargo test --all-features -- --test-threads=1
      - name: Run tests with minilp
        run: cargo test --no-default-features --features minilp
      - name: Run tests with lpsolve
        run: cargo test --no-default-features --features lpsolve
      - name: Run tests with highs
        run: cargo test --no-default-features --features highs
      - name: Run tests with lp_solvers
        run: cargo test --no-default-features --features lp-solvers
      - name: Check formatting
        run: cargo fmt -- --check
      - run: cargo bench
